### ISSUE TITLE
图片选择组件

### ISSUE THREAD

**Issue by xvbing** [reactnativecn/react-native-website#405]
react-native-image-picker 这图片选择器引入都没使用 直接就运行报错了 有谁搞过的吗  可以指点一下的吗
按照教程都配置过了 还是有问题
react-native-syan-image-picker 这个也试过了 也是直接就报错 
应该是有哪个地方没搞对

**Comment by sunnylqm** [comment]
原生组件一般都有额外的link步骤



---Original---
From: ***@***.***&gt;
Sent at: 2021年3月20日(Sat) Noon11:39
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [reactnativecn/react-native-website] 图片选择组件 (#405)




 
react-native-image-picker 这图片选择器引入都没使用 直接就运行报错了 有谁搞过的吗  可以指点一下的吗
 按照教程都配置过了 还是有问题
 react-native-syan-image-picker 这个也试过了 也是直接就报错
 应该是有哪个地方没搞对

**Comment by xvbing** [comment]
> 原生组件一般都有额外的link步骤
> […](#)
> ---Original--- From: ***@***.***&gt; Sent at: 2021年3月20日(Sat) Noon11:39 To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [reactnativecn/react-native-website] 图片选择组件 (#405) react-native-image-picker 这图片选择器引入都没使用 直接就运行报错了 有谁搞过的吗 可以指点一下的吗 按照教程都配置过了 还是有问题 react-native-syan-image-picker 这个也试过了 也是直接就报错 应该是有哪个地方没搞对 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

知道怎么link吗 我按网上的也操作过 没啥用

**Comment by sunnylqm** [comment]
各自的文档里都有详细的说明，不同版本做法也不同。link完之后也需要重新编译。



---Original---
From: ***@***.***&gt;
Sent at: 2021年3月20日(Sat) Noon1:51
To: ***@***.***&gt;;
Cc: "Sunny ***@***.******@***.***&gt;;
Subject: Re: [reactnativecn/react-native-website] 图片选择组件 (#405)




  
原生组件一般都有额外的link步骤
 …
 ---Original--- From: @.&gt; Sent at: 2021年3月20日(Sat) Noon11:39 To: @.&gt;; Cc: @.***&gt;; Subject: [reactnativecn/react-native-website] 图片选择组件 (#405) react-native-image-picker 这图片选择器引入都没使用 直接就运行报错了 有谁搞过的吗 可以指点一下的吗 按照教程都配置过了 还是有问题 react-native-syan-image-picker 这个也试过了 也是直接就报错 应该是有哪个地方没搞对 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
知道怎么link吗 我按网上的也操作过 没啥用

**Comment by DBAAZzz** [comment]
RN版本大于0.6的话android环境是不需要手动link的，可以检查一下grade有没有设置好环境变量
