### ISSUE TITLE
gradle 8.6在windows下可能存在bug，需降级到8.5

### ISSUE THREAD

**Issue by wang333333333** [reactnativecn/react-native-website#848]
![image](https://github.com/reactnativecn/react-native-website/assets/615282/a185905f-4638-44f6-bbe3-05fd2c8efd52)

---

E:\react\AwesomeProject>npx react-native info
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.19045
  CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Memory: 3.60 GB / 15.90 GB
Binaries:
  Node:
    version: 18.15.0
    path: E:\nvm\nodejs\node.EXE
  Yarn:
    version: 3.6.4
    path: E:\nvm\nodejs\yarn.CMD
  npm:
    version: 9.5.0
    path: E:\nvm\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 17.0.11
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.2
    wanted: 0.74.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

javac版本 17.0.11

**Comment by sunnylqm** [comment]
具体的报错呢？

**Comment by wang333333333** [comment]
failed to install the app

**Comment by sunnylqm** [comment]
这不是报错，截图

**Comment by wang333333333** [comment]
![微信图片_20240618191834](https://github.com/reactnativecn/react-native-website/assets/70459692/b6f843e3-fbd0-4caf-91c4-17b0d6a6846f)

**Comment by wang333333333** [comment]
![微信图片_20240618191924](https://github.com/reactnativecn/react-native-website/assets/70459692/c6898ee9-92fb-42ed-9a44-579244796643)

**Comment by sunnylqm** [comment]
删掉 `e:\react\awesomeproject\android\.gradle` 目录再重试

**Comment by Cz2545481217** [comment]
我也遇到了同样的问题，也尝试了删除.gradle,依然error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8082 FAILURE: Build failed with an exception. * What went 
wrong: A problem occurred configuring root project 'Web'. > Could not determine the dependencies of null. > Could not resolve all task dependencies for configuration ':classpath'. 
> Could not find com.android.tools.build:gradle:. Required by: project : > Could not resolve com.facebook.react:react-native-gradle-plugin. Required by: project : > No matching var
iant of project :gradle-plugin was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies decl
ared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.6' but: - Variant 'apiElements' capability com.facebook.react:react-native-gradle-plugin:unspeci
fied declares a library, packaged as a jar, and its dependencies declared externally: - Incompatible because this component declares a component for use during compile-time, compat
ible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8 - Other compatible attribute: - Doesn't say anything about org.gradle.plugin.ap
i-version (required '8.6') - Variant 'mainSourceElements' capability com.facebook.react:react-native-gradle-plugin:unspecified declares a component, and its dependencies declared e
xternally: - Incompatible because this component declares a component of category 'verification' and the consumer needed a library - Other compatible attributes: - Doesn't say anyt
hing about its target Java version (required compatibility with Java 8) - Doesn't say anything about its elements (required them packaged as a jar) - Doesn't say anything about org
.gradle.plugin.api-version (required '8.6') - Doesn't say anything about its usage (required runtime) - Variant 'runtimeElements' capability com.facebook.react:react-native-gradle-
plugin:unspecified declares a library for use during runtime, packaged as a jar, and its dependencies declared externally: - Incompatible because this component declares a componen
t, compatible with Java 11 and the consumer needed a component, compatible with Java 8 - Other compatible attribute: - Doesn't say anything about org.gradle.plugin.api-version (req
uired '8.6') - Variant 'testResultsElementsForTest' capability com.facebook.react:react-native-gradle-plugin:unspecified: - Incompatible because this component declares a component
 of category 'verification' and the consumer needed a library - Other compatible attributes: - Doesn't say anything about how its dependencies are found (required its dependencies declared externally) - Doesn't say anything about its target Java version (required compatibility with Java 8) - Doesn't say anything about its elements (required them packaged as a jar) - Doesn't say anything about org.gradle.plugin.api-version (required '8.6') - Doesn't say anything about its usage (required runtime) > Could not find org.jetbrains.kotlin:kotlin-gradle-plugin:. Required by: project : * Try: > Review the variant matching algorithm at https://docs.gradle.org/8.6/userguide/variant_attributes.html#sec:abm_algorithm. > No matching variant errors are explained in more detail at https://docs.gradle.org/8.6/userguide/variant_model.html#sub:variant-no-match. > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 5s.      
info Run CLI with --verbose flag for more details.

**Comment by wang333333333** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/70459692/bd6c61d0-c8f6-4d28-8436-c39e035282ce)
还是一样报错

> 删掉 `e:\react\awesomeproject\android\.gradle` 目录再重试

**Comment by wang333333333** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/70459692/a1555f3f-40cc-4645-9dbe-a300de30dcef)

**Comment by sunnylqm** [comment]
@Cz2545481217 你的问题完全不一样，你的是jdk版本不对

**Comment by sunnylqm** [comment]
@wang333333333 我查了下，好像是gradle 8.6的bug，

<img width="753" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/615282/61a8b7dd-2394-4da0-ad3c-c3ed8bdc0058">

降级到8.5可解决

**Comment by wang333333333** [comment]
> @wang333333333 我查了下，好像是gradle 8.6的bug，
> 
> <img alt="image" width="753" src="https://private-user-images.githubusercontent.com/615282/340893219-61a8b7dd-2394-4da0-ad3c-c3ed8bdc0058.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjQ4NjAsIm5iZiI6MTcxODc2NDU2MCwicGF0aCI6Ii82MTUyODIvMzQwODkzMjE5LTYxYThiN2RkLTIzOTQtNGRhMC1hZDNjLWMzZWQ4YmRjMDA1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwMjM2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2M2ZjllNjNkYjVlMjUwNGM1MTQ2YzNmMzhlM2YxNDI5ZTE5MGQ3NWNhYjhlNTNkMWJlZjk1NzZlZGRhODhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.heEw1jOWsftJJ-pyIV8uuBibl8x9Dr4HsSaQVZG4Iys">
> 降级到8.5可解决

![image](https://github.com/reactnativecn/react-native-website/assets/70459692/3703f601-8c80-45fe-bfb9-69d9a5bc861d)
降级到8.5也不行

**Comment by wang333333333** [comment]
降级到8.5之后 再删除.gradle 重新跑就可以了

**Comment by blackHairSnow** [comment]
确实降级之后就解决了  但是这个原理是什么  它报得是workspace  和 location

**Comment by tgwstyle** [comment]
@sunnylqm 
大佬,我这边将8.6降到8.5,并删除.gradle之后,重新运行,还是报错
![image](https://github.com/user-attachments/assets/2f2ae99d-d6ac-44bb-b0d6-4235bba41b86)

使用命令npx react-native doctor
![image](https://github.com/user-attachments/assets/d4052f01-1729-4eb3-80f7-a2c341d435cf)

npx react-native info
![image](https://github.com/user-attachments/assets/629c653c-e192-4717-8e31-f5525a61ada5)


求助大佬

**Comment by sunnylqm** [comment]
@tgwstyle 这个报错不是很明确，之前大部分人是因为jdk版本不对，但看这里的说法也可能还是网络的问题
https://github.com/reactnativecn/react-native-website/issues/838#issuecomment-2252078065
